### ISSUE TITLE
Don't print tags for volunteers

### ISSUE THREAD

**Issue by ema1brody2** [petereit/CheckinAir#24] opened 2018-08-22 20:58 UTC
Hi there,
We are new to CheckinAir.  Thank you for using your personal time to make check in easier in Corvallis Oregon :).  I have two issues that may just be user (me) errors.
#1.  The program logs me out after an unknown period of time.  Is there a setting somewhere that I am missing to stop this from happening?  I want to remain logged in until I shut down for the day.
#2.  I tell Breeze to not print tags for the volunteer team members, but when they check in usingCheckinAir it keeps printing a name tag and a parent security tag for them anyway.  How do I make it stop printing volunteer members (they are not clicked on tagged people to print labels for in my Breeze settings, but they are on the list of people who can check in.)

**Comment by petereit** [comment] 2018-08-23 08:54
I’m glad you’re finding my app useful!

1. I don’t have a timeout programmed in my app. I’ll ask my media director if he knows of a setting in Breeze. 

2. That probably is an issue with my app. Can you post an image of the screen where you have this set up in Breeze? I’ll need to configure my system to match it so I can run some tests.

**Comment by ema1brody2** [comment] 2018-08-23 21:34
Great information.  With your guidance, we were able to find the setting in Breeze to shut off the auto log out feature!  Here is a picture of the area in the Breeze event settings tab where it allows you to customize which tags get a label printed.
![breeze](https://user-images.githubusercontent.com/42623317/44553135-69579500-a6e1-11e8-8600-fd148c2e6f3d.jpg)

**Comment by petereit** [comment] 2018-08-25 16:15
I'm working on the volunteer tag issue now. Would you mind posting where you found the screen timeout setting in Breeze? (In case someone else encounters this issue in the future.)

Thanks!

**Comment by petereit** [comment] 2018-08-25 16:52
I think I have my system set up similar to yours, I have assigned myself to a group and set that group to not print on checkin. It looks like Breeze itself is still sending the value that the label should be printing. 

It might still be an issue with the way that I have configured my system for testing, so I have contacted Breeze to see if they can help me confirm if the issue is actually in their system, or if I missed something in my setup.

I'll keep you posted.

**Comment by petereit** [comment] 2018-08-28 19:04
Breeze has contacted me and indicates that the issue with labels printing when they shouldn’t may be in their system. They’ll let me know as soon as a fix is in. 

I also have a related update that needs to be pushed to the Apple store. Hopefully we’ll bith have our updates pushed out by this weekend.

**Comment by ema1brody2** [comment] 2018-08-28 19:08
You are amazing!  Thank you.

**Comment by sp20uth** [comment] 2018-08-29 20:49
Thanks for all you do with the App it is beneficial to us. We are once again having an issue with the additional label printing function from #19. But now it prints the additional name tag even if the specific tag isn't selected to print the additional label. I'm wondering if it connected to the issue in this thread.

**Comment by petereit** [comment] 2018-08-29 22:41
Thanks for letting me know. I should have some time to look at it on Friday. Hopefully I can get a fix pushed in time for an update before Sunday.

**Comment by sp20uth** [comment] 2018-08-29 22:49
Thank you very much. I really appreciate your work on the app. 

Steve

**Comment by shelbycrossings** [comment] 2018-09-26 17:41
Knowing that you are in SC, I feel badly about contacting you.  I do hope your area was not severely affected by the recent hurricane and that you and yours are safe.

If you are safe and have time to consider this comment and can help us with the new update you were developing, we would be most grateful.  We are using the Brother printer with your "3rd party app," and most things work great.  However, our problem is getting the iPad and the printer to talk to each other about who needs a name tag and who doesn't.  Children and Preschoolers enter through the same check-in door.  Preschoolers NEED a name tag, but the children do not.  Breeze has double checked our settings with the Dymo printer, and we have the settings correct for this.  However, the Brother printer prints everyone a name tag.  

It appears that this is similar to the worker situation discussed about a month ago.  Was this ever resolved?

Shellyn Poole
The Church at Shelby Crossings
Calera, AL

**Comment by petereit** [comment] 2018-09-26 17:48
No worries. I’m high and dry. I just pushed version 1.36 of the app this weekend that may actually resolve this issue for you. 

Mark

**Comment by shelbycrossings** [comment] 2018-09-27 00:36
Mark, we updated the iPads, but it's still printing the kids' name tags as well as the preschoolers'.  Thank you for your extra work on this.  I'll keep watching for additional updates.  

Shellyn

**Comment by petereit** [comment] 2018-09-29 16:19
I'm pretty sure I finally worked out Breeze's logic for printing tags or not. Please update to version 1.37 when it hits the app store.

**Closed by petereit** 2018-09-29 16:19 UTC
